apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-happypanda-deployment
  labels:
    name: helloworld-happypanda-deployment
spec:
  selector:
    matchLabels:
      app: helloworld-happypanda
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld-happypanda
    spec:
      containers:
      - name: helloworld-happypanda-pod
        image: docker.io/andresguisado/helloworld-happypanda:3.0.0
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - /bin/ls 
            - /tmp/ready
          initialDelaySeconds: 2
          timeoutSeconds: 1
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
          requests:
            memory: "32Mi"
            cpu: "250m"
        volumeMounts:
          - name: helloworld-happypanda-configmaps
            mountPath: /usr/share/nginx/html/configmaps
          - name: helloworld-happypanda-secrets
            mountPath: /usr/share/nginx/html/secrets
      volumes:
      - name: helloworld-happypanda-configmaps
        configMap:
          name: helloworld-happypanda-configmap
          items:
          - key: APP_CONFIG
            path: app_config.json
      - name: helloworld-happypanda-secrets
        secret:
          secretName: helloworld-happypanda-secret
          items:
          - key: APP_SECRET
            path: app_secret.json
      