apiVersion: v1
kind: Service
metadata:
  labels:
    name: helloworld-happypanda-service
  name: helloworld-happypanda-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: helloworld-happypanda